# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\documenti\dev\postgisQueryBuilder\ui_postgisquerybuilder.ui'
#
# Created: Thu Oct 09 11:31:50 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_postgisQueryBuilder(object):
    def setupUi(self, postgisQueryBuilder):
        postgisQueryBuilder.setObjectName(_fromUtf8("postgisQueryBuilder"))
        postgisQueryBuilder.resize(639, 525)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(postgisQueryBuilder.sizePolicy().hasHeightForWidth())
        postgisQueryBuilder.setSizePolicy(sizePolicy)
        self.ButtonReset = QtGui.QPushButton(postgisQueryBuilder)
        self.ButtonReset.setGeometry(QtCore.QRect(440, 490, 91, 25))
        self.ButtonReset.setObjectName(_fromUtf8("ButtonReset"))
        self.ButtonClose = QtGui.QPushButton(postgisQueryBuilder)
        self.ButtonClose.setGeometry(QtCore.QRect(540, 490, 90, 25))
        self.ButtonClose.setObjectName(_fromUtf8("ButtonClose"))
        self.tabWidget = QtGui.QToolBox(postgisQueryBuilder)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 621, 471))
        self.tabWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.ConnectionSlot = QtGui.QWidget()
        self.ConnectionSlot.setGeometry(QtCore.QRect(0, 0, 621, 255))
        self.ConnectionSlot.setObjectName(_fromUtf8("ConnectionSlot"))
        self.DBSchema = QtGui.QComboBox(self.ConnectionSlot)
        self.DBSchema.setGeometry(QtCore.QRect(210, 16, 180, 22))
        self.DBSchema.setObjectName(_fromUtf8("DBSchema"))
        self.DBSchemaLabel = QtGui.QLabel(self.ConnectionSlot)
        self.DBSchemaLabel.setGeometry(QtCore.QRect(210, -4, 181, 16))
        self.DBSchemaLabel.setObjectName(_fromUtf8("DBSchemaLabel"))
        self.PSQLConnectionLabel = QtGui.QLabel(self.ConnectionSlot)
        self.PSQLConnectionLabel.setGeometry(QtCore.QRect(0, 1, 181, 16))
        self.PSQLConnectionLabel.setObjectName(_fromUtf8("PSQLConnectionLabel"))
        self.PSQLConnection = QtGui.QComboBox(self.ConnectionSlot)
        self.PSQLConnection.setGeometry(QtCore.QRect(0, 20, 180, 20))
        self.PSQLConnection.setObjectName(_fromUtf8("PSQLConnection"))
        self.KEYFIELDLabel = QtGui.QLabel(self.ConnectionSlot)
        self.KEYFIELDLabel.setGeometry(QtCore.QRect(0, 50, 181, 16))
        self.KEYFIELDLabel.setObjectName(_fromUtf8("KEYFIELDLabel"))
        self.GEOMETRYFIELDLabel = QtGui.QLabel(self.ConnectionSlot)
        self.GEOMETRYFIELDLabel.setGeometry(QtCore.QRect(105, 50, 171, 16))
        self.GEOMETRYFIELDLabel.setObjectName(_fromUtf8("GEOMETRYFIELDLabel"))
        self.KEYFIELD = QtGui.QLineEdit(self.ConnectionSlot)
        self.KEYFIELD.setGeometry(QtCore.QRect(0, 68, 90, 20))
        self.KEYFIELD.setObjectName(_fromUtf8("KEYFIELD"))
        self.GEOMETRYFIELD = QtGui.QLineEdit(self.ConnectionSlot)
        self.GEOMETRYFIELD.setGeometry(QtCore.QRect(105, 68, 90, 20))
        self.GEOMETRYFIELD.setObjectName(_fromUtf8("GEOMETRYFIELD"))
        self.tabWidget.addItem(self.ConnectionSlot, _fromUtf8(""))
        self.availableLayersSlot = QtGui.QWidget()
        self.availableLayersSlot.setGeometry(QtCore.QRect(0, 0, 621, 255))
        self.availableLayersSlot.setObjectName(_fromUtf8("availableLayersSlot"))
        self.label_2 = QtGui.QLabel(self.availableLayersSlot)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 371, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.GetInfoButton = QtGui.QPushButton(self.availableLayersSlot)
        self.GetInfoButton.setGeometry(QtCore.QRect(500, 50, 90, 23))
        self.GetInfoButton.setObjectName(_fromUtf8("GetInfoButton"))
        self.DeleteButton = QtGui.QPushButton(self.availableLayersSlot)
        self.DeleteButton.setGeometry(QtCore.QRect(500, 80, 90, 23))
        self.DeleteButton.setObjectName(_fromUtf8("DeleteButton"))
        self.RefreshButton = QtGui.QPushButton(self.availableLayersSlot)
        self.RefreshButton.setGeometry(QtCore.QRect(500, 110, 90, 23))
        self.RefreshButton.setObjectName(_fromUtf8("RefreshButton"))
        self.AddToMapButton = QtGui.QPushButton(self.availableLayersSlot)
        self.AddToMapButton.setGeometry(QtCore.QRect(500, 20, 90, 23))
        self.AddToMapButton.setObjectName(_fromUtf8("AddToMapButton"))
        self.LayerList = QtGui.QListWidget(self.availableLayersSlot)
        self.LayerList.setGeometry(QtCore.QRect(0, 20, 491, 261))
        self.LayerList.setObjectName(_fromUtf8("LayerList"))
        self.tabWidget.addItem(self.availableLayersSlot, _fromUtf8(""))
        self.queryTypeSlot = QtGui.QWidget()
        self.queryTypeSlot.setGeometry(QtCore.QRect(0, 0, 621, 255))
        self.queryTypeSlot.setObjectName(_fromUtf8("queryTypeSlot"))
        self.Helper2 = QtGui.QLabel(self.queryTypeSlot)
        self.Helper2.setGeometry(QtCore.QRect(10, 40, 151, 201))
        self.Helper2.setText(_fromUtf8(""))
        self.Helper2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Helper2.setWordWrap(True)
        self.Helper2.setObjectName(_fromUtf8("Helper2"))
        self.QueryType = QtGui.QComboBox(self.queryTypeSlot)
        self.QueryType.setGeometry(QtCore.QRect(6, 0, 211, 20))
        self.QueryType.setMaxVisibleItems(20)
        self.QueryType.setObjectName(_fromUtf8("QueryType"))
        self.ButtonHelp = QtGui.QPushButton(self.queryTypeSlot)
        self.ButtonHelp.setGeometry(QtCore.QRect(460, 0, 161, 25))
        self.ButtonHelp.setObjectName(_fromUtf8("ButtonHelp"))
        self.DiagPanel = QtGui.QGraphicsView(self.queryTypeSlot)
        self.DiagPanel.setGeometry(QtCore.QRect(180, 40, 441, 211))
        self.DiagPanel.setAcceptDrops(False)
        self.DiagPanel.setStyleSheet(_fromUtf8("color: rgba(212, 208, 200, 0)"))
        self.DiagPanel.setFrameShape(QtGui.QFrame.NoFrame)
        self.DiagPanel.setFrameShadow(QtGui.QFrame.Raised)
        self.DiagPanel.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DiagPanel.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.DiagPanel.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.DiagPanel.setForegroundBrush(brush)
        self.DiagPanel.setInteractive(False)
        self.DiagPanel.setObjectName(_fromUtf8("DiagPanel"))
        self.tabWidget.addItem(self.queryTypeSlot, _fromUtf8(""))
        self.queryDefinitionSlot = QtGui.QWidget()
        self.queryDefinitionSlot.setGeometry(QtCore.QRect(0, 0, 621, 255))
        self.queryDefinitionSlot.setObjectName(_fromUtf8("queryDefinitionSlot"))
        self.CONDITIONLabel = QtGui.QLabel(self.queryDefinitionSlot)
        self.CONDITIONLabel.setGeometry(QtCore.QRect(310, 241, 151, 16))
        self.CONDITIONLabel.setObjectName(_fromUtf8("CONDITIONLabel"))
        self.LAYERaLabel = QtGui.QLabel(self.queryDefinitionSlot)
        self.LAYERaLabel.setGeometry(QtCore.QRect(10, 90, 151, 16))
        self.LAYERaLabel.setObjectName(_fromUtf8("LAYERaLabel"))
        self.JOINLabel = QtGui.QLabel(self.queryDefinitionSlot)
        self.JOINLabel.setGeometry(QtCore.QRect(220, 240, 71, 16))
        self.JOINLabel.setObjectName(_fromUtf8("JOINLabel"))
        self.SPATIALRELLabel = QtGui.QLabel(self.queryDefinitionSlot)
        self.SPATIALRELLabel.setGeometry(QtCore.QRect(5, 241, 281, 16))
        self.SPATIALRELLabel.setObjectName(_fromUtf8("SPATIALRELLabel"))
        self.DISTANCE = QtGui.QLineEdit(self.queryDefinitionSlot)
        self.DISTANCE.setGeometry(QtCore.QRect(100, 260, 113, 20))
        self.DISTANCE.setObjectName(_fromUtf8("DISTANCE"))
        self.SPATIALRELNOT = QtGui.QCheckBox(self.queryDefinitionSlot)
        self.SPATIALRELNOT.setGeometry(QtCore.QRect(310, 260, 50, 18))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SPATIALRELNOT.sizePolicy().hasHeightForWidth())
        self.SPATIALRELNOT.setSizePolicy(sizePolicy)
        self.SPATIALRELNOT.setMaximumSize(QtCore.QSize(50, 16777215))
        self.SPATIALRELNOT.setObjectName(_fromUtf8("SPATIALRELNOT"))
        self.LAYERa = QtGui.QComboBox(self.queryDefinitionSlot)
        self.LAYERa.setGeometry(QtCore.QRect(10, 107, 300, 20))
        self.LAYERa.setObjectName(_fromUtf8("LAYERa"))
        self.BUFFERRADIUS = QtGui.QLineEdit(self.queryDefinitionSlot)
        self.BUFFERRADIUS.setGeometry(QtCore.QRect(5, 260, 170, 20))
        self.BUFFERRADIUS.setObjectName(_fromUtf8("BUFFERRADIUS"))
        self.DISTANCELabel = QtGui.QLabel(self.queryDefinitionSlot)
        self.DISTANCELabel.setGeometry(QtCore.QRect(100, 241, 151, 16))
        self.DISTANCELabel.setObjectName(_fromUtf8("DISTANCELabel"))
        self.fieldsListA = QtGui.QListWidget(self.queryDefinitionSlot)
        self.fieldsListA.setGeometry(QtCore.QRect(10, 127, 300, 101))
        self.fieldsListA.setMinimumSize(QtCore.QSize(150, 0))
        self.fieldsListA.setObjectName(_fromUtf8("fieldsListA"))
        self.FIELD = QtGui.QComboBox(self.queryDefinitionSlot)
        self.FIELD.setGeometry(QtCore.QRect(5, 260, 214, 20))
        self.FIELD.setObjectName(_fromUtf8("FIELD"))
        self.fieldsListB = QtGui.QListWidget(self.queryDefinitionSlot)
        self.fieldsListB.setGeometry(QtCore.QRect(315, 127, 300, 101))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldsListB.sizePolicy().hasHeightForWidth())
        self.fieldsListB.setSizePolicy(sizePolicy)
        self.fieldsListB.setMinimumSize(QtCore.QSize(0, 0))
        self.fieldsListB.setMaximumSize(QtCore.QSize(16777215, 25000))
        self.fieldsListB.setObjectName(_fromUtf8("fieldsListB"))
        self.FIELDbLabel = QtGui.QLabel(self.queryDefinitionSlot)
        self.FIELDbLabel.setGeometry(QtCore.QRect(300, 241, 201, 16))
        self.FIELDbLabel.setObjectName(_fromUtf8("FIELDbLabel"))
        self.BUFFERRADIUSLabel = QtGui.QLabel(self.queryDefinitionSlot)
        self.BUFFERRADIUSLabel.setGeometry(QtCore.QRect(5, 241, 281, 16))
        self.BUFFERRADIUSLabel.setObjectName(_fromUtf8("BUFFERRADIUSLabel"))
        self.OPERATOR = QtGui.QComboBox(self.queryDefinitionSlot)
        self.OPERATOR.setGeometry(QtCore.QRect(224, 260, 81, 20))
        self.OPERATOR.setObjectName(_fromUtf8("OPERATOR"))
        self.DISTANCEOP = QtGui.QComboBox(self.queryDefinitionSlot)
        self.DISTANCEOP.setGeometry(QtCore.QRect(5, 260, 81, 20))
        self.DISTANCEOP.setObjectName(_fromUtf8("DISTANCEOP"))
        self.FIELDLabel = QtGui.QLabel(self.queryDefinitionSlot)
        self.FIELDLabel.setGeometry(QtCore.QRect(5, 241, 201, 16))
        self.FIELDLabel.setObjectName(_fromUtf8("FIELDLabel"))
        self.LAYERbLabel = QtGui.QLabel(self.queryDefinitionSlot)
        self.LAYERbLabel.setGeometry(QtCore.QRect(315, 90, 161, 16))
        self.LAYERbLabel.setObjectName(_fromUtf8("LAYERbLabel"))
        self.SPATIALREL = QtGui.QComboBox(self.queryDefinitionSlot)
        self.SPATIALREL.setGeometry(QtCore.QRect(5, 260, 300, 20))
        self.SPATIALREL.setObjectName(_fromUtf8("SPATIALREL"))
        self.LAYERb = QtGui.QComboBox(self.queryDefinitionSlot)
        self.LAYERb.setGeometry(QtCore.QRect(315, 107, 300, 20))
        self.LAYERb.setObjectName(_fromUtf8("LAYERb"))
        self.OPERATORLabel = QtGui.QLabel(self.queryDefinitionSlot)
        self.OPERATORLabel.setGeometry(QtCore.QRect(224, 241, 98, 16))
        self.OPERATORLabel.setObjectName(_fromUtf8("OPERATORLabel"))
        self.FIELDb = QtGui.QComboBox(self.queryDefinitionSlot)
        self.FIELDb.setGeometry(QtCore.QRect(300, 260, 214, 20))
        self.FIELDb.setObjectName(_fromUtf8("FIELDb"))
        self.JOIN = QtGui.QComboBox(self.queryDefinitionSlot)
        self.JOIN.setGeometry(QtCore.QRect(220, 260, 74, 20))
        self.JOIN.setObjectName(_fromUtf8("JOIN"))
        self.queryReadyButton = QtGui.QPushButton(self.queryDefinitionSlot)
        self.queryReadyButton.setGeometry(QtCore.QRect(570, 245, 35, 35))
        self.queryReadyButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("querybuilderlogo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.queryReadyButton.setIcon(icon)
        self.queryReadyButton.setIconSize(QtCore.QSize(30, 30))
        self.queryReadyButton.setFlat(True)
        self.queryReadyButton.setObjectName(_fromUtf8("queryReadyButton"))
        self.CONDITION = QtGui.QComboBox(self.queryDefinitionSlot)
        self.CONDITION.setGeometry(QtCore.QRect(310, 260, 151, 20))
        self.CONDITION.setEditable(True)
        self.CONDITION.setObjectName(_fromUtf8("CONDITION"))
        self.DISTANCEOPLabel = QtGui.QLabel(self.queryDefinitionSlot)
        self.DISTANCEOPLabel.setGeometry(QtCore.QRect(5, 241, 98, 16))
        self.DISTANCEOPLabel.setObjectName(_fromUtf8("DISTANCEOPLabel"))
        self.Helper = QtGui.QLabel(self.queryDefinitionSlot)
        self.Helper.setGeometry(QtCore.QRect(5, 0, 605, 81))
        self.Helper.setAutoFillBackground(False)
        self.Helper.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Helper.setText(_fromUtf8(""))
        self.Helper.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Helper.setWordWrap(True)
        self.Helper.setObjectName(_fromUtf8("Helper"))
        self.selectAllFields = QtGui.QCheckBox(self.queryDefinitionSlot)
        self.selectAllFields.setGeometry(QtCore.QRect(275, 90, 41, 18))
        self.selectAllFields.setObjectName(_fromUtf8("selectAllFields"))
        self.tabWidget.addItem(self.queryDefinitionSlot, _fromUtf8(""))
        self.filterRecordSlot = QtGui.QWidget()
        self.filterRecordSlot.setGeometry(QtCore.QRect(0, 0, 621, 255))
        self.filterRecordSlot.setObjectName(_fromUtf8("filterRecordSlot"))
        self.filterTable = tableSet(self.filterRecordSlot)
        self.filterTable.setGeometry(QtCore.QRect(0, 10, 621, 211))
        self.filterTable.setShowGrid(False)
        self.filterTable.setObjectName(_fromUtf8("filterTable"))
        self.filterTable.setColumnCount(0)
        self.filterTable.setRowCount(0)
        self.filterTable.horizontalHeader().setVisible(False)
        self.filterTable.verticalHeader().setVisible(False)
        self.labelOrderby = QtGui.QLabel(self.filterRecordSlot)
        self.labelOrderby.setGeometry(QtCore.QRect(0, 232, 71, 16))
        self.labelOrderby.setObjectName(_fromUtf8("labelOrderby"))
        self.orderBy = QtGui.QComboBox(self.filterRecordSlot)
        self.orderBy.setGeometry(QtCore.QRect(50, 230, 211, 22))
        self.orderBy.setObjectName(_fromUtf8("orderBy"))
        self.tabWidget.addItem(self.filterRecordSlot, _fromUtf8(""))
        self.SqlCodeSlot = QtGui.QWidget()
        self.SqlCodeSlot.setGeometry(QtCore.QRect(0, 0, 621, 255))
        self.SqlCodeSlot.setObjectName(_fromUtf8("SqlCodeSlot"))
        self.QueryResult = QtGui.QTextEdit(self.SqlCodeSlot)
        self.QueryResult.setGeometry(QtCore.QRect(0, 50, 621, 201))
        self.QueryResult.setObjectName(_fromUtf8("QueryResult"))
        self.QueryName = QtGui.QLineEdit(self.SqlCodeSlot)
        self.QueryName.setGeometry(QtCore.QRect(0, 20, 621, 20))
        self.QueryName.setObjectName(_fromUtf8("QueryName"))
        self.checkCreateView = QtGui.QCheckBox(self.SqlCodeSlot)
        self.checkCreateView.setGeometry(QtCore.QRect(5, 0, 81, 18))
        self.checkCreateView.setObjectName(_fromUtf8("checkCreateView"))
        self.checkMaterialized = QtGui.QCheckBox(self.SqlCodeSlot)
        self.checkMaterialized.setGeometry(QtCore.QRect(90, 0, 111, 18))
        self.checkMaterialized.setObjectName(_fromUtf8("checkMaterialized"))
        self.tabWidget.addItem(self.SqlCodeSlot, _fromUtf8(""))
        self.tableResultSlot = QtGui.QWidget()
        self.tableResultSlot.setGeometry(QtCore.QRect(0, 0, 621, 255))
        self.tableResultSlot.setObjectName(_fromUtf8("tableResultSlot"))
        self.TableResult = QtGui.QTableWidget(self.tableResultSlot)
        self.TableResult.setGeometry(QtCore.QRect(0, 0, 621, 241))
        self.TableResult.setObjectName(_fromUtf8("TableResult"))
        self.TableResult.setColumnCount(0)
        self.TableResult.setRowCount(0)
        self.TableResult.horizontalHeader().setMinimumSectionSize(25)
        self.TableResult.verticalHeader().setDefaultSectionSize(25)
        self.labelRowsNumber = QtGui.QLabel(self.tableResultSlot)
        self.labelRowsNumber.setGeometry(QtCore.QRect(0, 240, 621, 16))
        self.labelRowsNumber.setText(_fromUtf8(""))
        self.labelRowsNumber.setObjectName(_fromUtf8("labelRowsNumber"))
        self.tabWidget.addItem(self.tableResultSlot, _fromUtf8(""))
        self.historySlot = QtGui.QWidget()
        self.historySlot.setGeometry(QtCore.QRect(0, 0, 621, 255))
        self.historySlot.setObjectName(_fromUtf8("historySlot"))
        self.historyLog = QtGui.QPlainTextEdit(self.historySlot)
        self.historyLog.setGeometry(QtCore.QRect(0, 0, 621, 261))
        self.historyLog.setReadOnly(True)
        self.historyLog.setObjectName(_fromUtf8("historyLog"))
        self.tabWidget.addItem(self.historySlot, _fromUtf8(""))
        self.AddToMap = QtGui.QCheckBox(postgisQueryBuilder)
        self.AddToMap.setGeometry(QtCore.QRect(110, 493, 116, 18))
        self.AddToMap.setChecked(True)
        self.AddToMap.setObjectName(_fromUtf8("AddToMap"))
        self.ButtonRun = QtGui.QPushButton(postgisQueryBuilder)
        self.ButtonRun.setGeometry(QtCore.QRect(10, 490, 90, 25))
        self.ButtonRun.setObjectName(_fromUtf8("ButtonRun"))

        self.retranslateUi(postgisQueryBuilder)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(postgisQueryBuilder)

    def retranslateUi(self, postgisQueryBuilder):
        postgisQueryBuilder.setWindowTitle(_translate("postgisQueryBuilder", "postgisQueryBuilder", None))
        self.ButtonReset.setText(_translate("postgisQueryBuilder", "reset form", None))
        self.ButtonClose.setText(_translate("postgisQueryBuilder", "close", None))
        self.DBSchemaLabel.setText(_translate("postgisQueryBuilder", "Schema", None))
        self.PSQLConnectionLabel.setText(_translate("postgisQueryBuilder", "Postgresql connection", None))
        self.KEYFIELDLabel.setText(_translate("postgisQueryBuilder", "Key field", None))
        self.GEOMETRYFIELDLabel.setText(_translate("postgisQueryBuilder", "Geometry field", None))
        self.tabWidget.setItemText(self.tabWidget.indexOf(self.ConnectionSlot), _translate("postgisQueryBuilder", "Connection defaults", None))
        self.label_2.setText(_translate("postgisQueryBuilder", "Available relations list (T:table V:view M:materialized view)", None))
        self.GetInfoButton.setText(_translate("postgisQueryBuilder", "Get table", None))
        self.DeleteButton.setText(_translate("postgisQueryBuilder", "Delete", None))
        self.RefreshButton.setText(_translate("postgisQueryBuilder", "Refresh", None))
        self.AddToMapButton.setText(_translate("postgisQueryBuilder", "Add to map", None))
        self.tabWidget.setItemText(self.tabWidget.indexOf(self.availableLayersSlot), _translate("postgisQueryBuilder", "Available layers", None))
        self.ButtonHelp.setText(_translate("postgisQueryBuilder", "Help ", None))
        self.tabWidget.setItemText(self.tabWidget.indexOf(self.queryTypeSlot), _translate("postgisQueryBuilder", "Query type", None))
        self.CONDITIONLabel.setText(_translate("postgisQueryBuilder", "Condition", None))
        self.LAYERaLabel.setText(_translate("postgisQueryBuilder", "Layer A", None))
        self.JOINLabel.setText(_translate("postgisQueryBuilder", "Join type", None))
        self.SPATIALRELLabel.setText(_translate("postgisQueryBuilder", "Spatial relationship between LayerA and Layer B", None))
        self.SPATIALRELNOT.setText(_translate("postgisQueryBuilder", "NOT", None))
        self.DISTANCELabel.setText(_translate("postgisQueryBuilder", "Condition", None))
        self.FIELDbLabel.setText(_translate("postgisQueryBuilder", "Select Field of Layer B", None))
        self.BUFFERRADIUSLabel.setText(_translate("postgisQueryBuilder", "Buffer radius", None))
        self.FIELDLabel.setText(_translate("postgisQueryBuilder", "Select Field of Layer A", None))
        self.LAYERbLabel.setText(_translate("postgisQueryBuilder", "Layer B", None))
        self.OPERATORLabel.setText(_translate("postgisQueryBuilder", "Operator", None))
        self.DISTANCEOPLabel.setText(_translate("postgisQueryBuilder", "Operator", None))
        self.selectAllFields.setText(_translate("postgisQueryBuilder", "All", None))
        self.tabWidget.setItemText(self.tabWidget.indexOf(self.queryDefinitionSlot), _translate("postgisQueryBuilder", "Query definition", None))
        self.labelOrderby.setText(_translate("postgisQueryBuilder", "Order by:", None))
        self.tabWidget.setItemText(self.tabWidget.indexOf(self.filterRecordSlot), _translate("postgisQueryBuilder", "Filter records", None))
        self.checkCreateView.setText(_translate("postgisQueryBuilder", "As view", None))
        self.checkMaterialized.setText(_translate("postgisQueryBuilder", "Materialized", None))
        self.tabWidget.setItemText(self.tabWidget.indexOf(self.SqlCodeSlot), _translate("postgisQueryBuilder", "SQL code", None))
        self.TableResult.setSortingEnabled(True)
        self.tabWidget.setItemText(self.tabWidget.indexOf(self.tableResultSlot), _translate("postgisQueryBuilder", "Table result", None))
        self.tabWidget.setItemText(self.tabWidget.indexOf(self.historySlot), _translate("postgisQueryBuilder", "History", None))
        self.AddToMap.setText(_translate("postgisQueryBuilder", "Add to map", None))
        self.ButtonRun.setText(_translate("postgisQueryBuilder", "Run query", None))

from TableSet import tableSet
