# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_postgisquerybuilder.ui'
#
# Created: Tue May 13 17:10:39 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_postgisQueryBuilder(object):
    def setupUi(self, postgisQueryBuilder):
        postgisQueryBuilder.setObjectName(_fromUtf8("postgisQueryBuilder"))
        postgisQueryBuilder.resize(358, 562)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(postgisQueryBuilder.sizePolicy().hasHeightForWidth())
        postgisQueryBuilder.setSizePolicy(sizePolicy)
        self.ButtonReset = QtGui.QPushButton(postgisQueryBuilder)
        self.ButtonReset.setGeometry(QtCore.QRect(190, 532, 77, 25))
        self.ButtonReset.setObjectName(_fromUtf8("ButtonReset"))
        self.ButtonClose = QtGui.QPushButton(postgisQueryBuilder)
        self.ButtonClose.setGeometry(QtCore.QRect(274, 532, 77, 25))
        self.ButtonClose.setObjectName(_fromUtf8("ButtonClose"))
        self.FIELDLabel = QtGui.QLabel(postgisQueryBuilder)
        self.FIELDLabel.setGeometry(QtCore.QRect(5, 307, 121, 16))
        self.FIELDLabel.setObjectName(_fromUtf8("FIELDLabel"))
        self.SPATIALRELLabel = QtGui.QLabel(postgisQueryBuilder)
        self.SPATIALRELLabel.setGeometry(QtCore.QRect(5, 307, 281, 16))
        self.SPATIALRELLabel.setObjectName(_fromUtf8("SPATIALRELLabel"))
        self.SPATIALREL = QtGui.QComboBox(postgisQueryBuilder)
        self.SPATIALREL.setGeometry(QtCore.QRect(5, 326, 281, 20))
        self.SPATIALREL.setObjectName(_fromUtf8("SPATIALREL"))
        self.BUFFERRADIUSLabel = QtGui.QLabel(postgisQueryBuilder)
        self.BUFFERRADIUSLabel.setGeometry(QtCore.QRect(5, 307, 62, 16))
        self.BUFFERRADIUSLabel.setObjectName(_fromUtf8("BUFFERRADIUSLabel"))
        self.QueryName = QtGui.QLineEdit(postgisQueryBuilder)
        self.QueryName.setGeometry(QtCore.QRect(149, 360, 201, 20))
        self.QueryName.setObjectName(_fromUtf8("QueryName"))
        self.OPERATORLabel = QtGui.QLabel(postgisQueryBuilder)
        self.OPERATORLabel.setGeometry(QtCore.QRect(180, 307, 98, 16))
        self.OPERATORLabel.setObjectName(_fromUtf8("OPERATORLabel"))
        self.PSQLConnection = QtGui.QComboBox(postgisQueryBuilder)
        self.PSQLConnection.setGeometry(QtCore.QRect(5, 115, 170, 20))
        self.PSQLConnection.setObjectName(_fromUtf8("PSQLConnection"))
        self.PSQLConnectionLabel = QtGui.QLabel(postgisQueryBuilder)
        self.PSQLConnectionLabel.setGeometry(QtCore.QRect(5, 96, 105, 16))
        self.PSQLConnectionLabel.setObjectName(_fromUtf8("PSQLConnectionLabel"))
        self.QueryType = QtGui.QComboBox(postgisQueryBuilder)
        self.QueryType.setGeometry(QtCore.QRect(5, 20, 251, 20))
        self.QueryType.setObjectName(_fromUtf8("QueryType"))
        self.ButtonHelp = QtGui.QPushButton(postgisQueryBuilder)
        self.ButtonHelp.setGeometry(QtCore.QRect(270, 20, 82, 20))
        self.ButtonHelp.setObjectName(_fromUtf8("ButtonHelp"))
        self.label = QtGui.QLabel(postgisQueryBuilder)
        self.label.setGeometry(QtCore.QRect(5, 5, 55, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.ButtonRun = QtGui.QPushButton(postgisQueryBuilder)
        self.ButtonRun.setGeometry(QtCore.QRect(5, 532, 77, 25))
        self.ButtonRun.setObjectName(_fromUtf8("ButtonRun"))
        self.CONDITIONLabel = QtGui.QLabel(postgisQueryBuilder)
        self.CONDITIONLabel.setGeometry(QtCore.QRect(240, 307, 45, 16))
        self.CONDITIONLabel.setObjectName(_fromUtf8("CONDITIONLabel"))
        self.AddToMap = QtGui.QCheckBox(postgisQueryBuilder)
        self.AddToMap.setGeometry(QtCore.QRect(90, 535, 116, 18))
        self.AddToMap.setChecked(True)
        self.AddToMap.setObjectName(_fromUtf8("AddToMap"))
        self.OPERATOR = QtGui.QComboBox(postgisQueryBuilder)
        self.OPERATOR.setGeometry(QtCore.QRect(180, 326, 55, 20))
        self.OPERATOR.setObjectName(_fromUtf8("OPERATOR"))
        self.CONDITION = QtGui.QComboBox(postgisQueryBuilder)
        self.CONDITION.setGeometry(QtCore.QRect(240, 326, 111, 20))
        self.CONDITION.setEditable(True)
        self.CONDITION.setObjectName(_fromUtf8("CONDITION"))
        self.LAYERbLabel = QtGui.QLabel(postgisQueryBuilder)
        self.LAYERbLabel.setGeometry(QtCore.QRect(180, 141, 36, 16))
        self.LAYERbLabel.setObjectName(_fromUtf8("LAYERbLabel"))
        self.LAYERa = QtGui.QComboBox(postgisQueryBuilder)
        self.LAYERa.setGeometry(QtCore.QRect(5, 160, 170, 20))
        self.LAYERa.setObjectName(_fromUtf8("LAYERa"))
        self.LAYERaLabel = QtGui.QLabel(postgisQueryBuilder)
        self.LAYERaLabel.setGeometry(QtCore.QRect(5, 141, 37, 16))
        self.LAYERaLabel.setObjectName(_fromUtf8("LAYERaLabel"))
        self.fieldsListA = QtGui.QListWidget(postgisQueryBuilder)
        self.fieldsListA.setGeometry(QtCore.QRect(5, 186, 170, 115))
        self.fieldsListA.setMinimumSize(QtCore.QSize(150, 0))
        self.fieldsListA.setObjectName(_fromUtf8("fieldsListA"))
        self.FIELD = QtGui.QComboBox(postgisQueryBuilder)
        self.FIELD.setGeometry(QtCore.QRect(5, 326, 170, 20))
        self.FIELD.setObjectName(_fromUtf8("FIELD"))
        self.BUFFERRADIUS = QtGui.QLineEdit(postgisQueryBuilder)
        self.BUFFERRADIUS.setGeometry(QtCore.QRect(5, 326, 170, 20))
        self.BUFFERRADIUS.setObjectName(_fromUtf8("BUFFERRADIUS"))
        self.fieldsListB = QtGui.QListWidget(postgisQueryBuilder)
        self.fieldsListB.setGeometry(QtCore.QRect(180, 186, 170, 115))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldsListB.sizePolicy().hasHeightForWidth())
        self.fieldsListB.setSizePolicy(sizePolicy)
        self.fieldsListB.setMinimumSize(QtCore.QSize(150, 115))
        self.fieldsListB.setMaximumSize(QtCore.QSize(16777215, 100))
        self.fieldsListB.setObjectName(_fromUtf8("fieldsListB"))
        self.SPATIALRELNOT = QtGui.QCheckBox(postgisQueryBuilder)
        self.SPATIALRELNOT.setGeometry(QtCore.QRect(300, 326, 45, 18))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SPATIALRELNOT.sizePolicy().hasHeightForWidth())
        self.SPATIALRELNOT.setSizePolicy(sizePolicy)
        self.SPATIALRELNOT.setMaximumSize(QtCore.QSize(50, 16777215))
        self.SPATIALRELNOT.setObjectName(_fromUtf8("SPATIALRELNOT"))
        self.checkCreateView = QtGui.QCheckBox(postgisQueryBuilder)
        self.checkCreateView.setGeometry(QtCore.QRect(5, 360, 61, 18))
        self.checkCreateView.setObjectName(_fromUtf8("checkCreateView"))
        self.GEOMETRYFIELD = QtGui.QLineEdit(postgisQueryBuilder)
        self.GEOMETRYFIELD.setGeometry(QtCore.QRect(180, 115, 82, 20))
        self.GEOMETRYFIELD.setObjectName(_fromUtf8("GEOMETRYFIELD"))
        self.GEOMETRYFIELDLabel = QtGui.QLabel(postgisQueryBuilder)
        self.GEOMETRYFIELDLabel.setGeometry(QtCore.QRect(180, 96, 70, 16))
        self.GEOMETRYFIELDLabel.setObjectName(_fromUtf8("GEOMETRYFIELDLabel"))
        self.KEYFIELD = QtGui.QLineEdit(postgisQueryBuilder)
        self.KEYFIELD.setGeometry(QtCore.QRect(270, 115, 82, 20))
        self.KEYFIELD.setObjectName(_fromUtf8("KEYFIELD"))
        self.KEYFIELDLabel = QtGui.QLabel(postgisQueryBuilder)
        self.KEYFIELDLabel.setGeometry(QtCore.QRect(270, 96, 41, 16))
        self.KEYFIELDLabel.setObjectName(_fromUtf8("KEYFIELDLabel"))
        self.LAYERb = QtGui.QComboBox(postgisQueryBuilder)
        self.LAYERb.setGeometry(QtCore.QRect(180, 160, 170, 20))
        self.LAYERb.setObjectName(_fromUtf8("LAYERb"))
        self.Helper = QtGui.QLabel(postgisQueryBuilder)
        self.Helper.setGeometry(QtCore.QRect(5, 45, 341, 51))
        self.Helper.setText(_fromUtf8(""))
        self.Helper.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Helper.setWordWrap(True)
        self.Helper.setObjectName(_fromUtf8("Helper"))
        self.checkMaterialized = QtGui.QCheckBox(postgisQueryBuilder)
        self.checkMaterialized.setGeometry(QtCore.QRect(70, 360, 81, 18))
        self.checkMaterialized.setObjectName(_fromUtf8("checkMaterialized"))
        self.tabWidget = QtGui.QTabWidget(postgisQueryBuilder)
        self.tabWidget.setGeometry(QtCore.QRect(5, 380, 345, 148))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.QueryTab = QtGui.QWidget()
        self.QueryTab.setObjectName(_fromUtf8("QueryTab"))
        self.QueryResult = QtGui.QPlainTextEdit(self.QueryTab)
        self.QueryResult.setGeometry(QtCore.QRect(0, 0, 339, 122))
        self.QueryResult.setObjectName(_fromUtf8("QueryResult"))
        self.tabWidget.addTab(self.QueryTab, _fromUtf8(""))
        self.TableTab = QtGui.QWidget()
        self.TableTab.setAccessibleName(_fromUtf8(""))
        self.TableTab.setObjectName(_fromUtf8("TableTab"))
        self.TableResult = QtGui.QTableWidget(self.TableTab)
        self.TableResult.setGeometry(QtCore.QRect(0, 0, 339, 122))
        self.TableResult.setObjectName(_fromUtf8("TableResult"))
        self.TableResult.setColumnCount(0)
        self.TableResult.setRowCount(0)
        self.TableResult.horizontalHeader().setMinimumSectionSize(25)
        self.TableResult.verticalHeader().setDefaultSectionSize(25)
        self.tabWidget.addTab(self.TableTab, _fromUtf8(""))

        self.retranslateUi(postgisQueryBuilder)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(postgisQueryBuilder)

    def retranslateUi(self, postgisQueryBuilder):
        postgisQueryBuilder.setWindowTitle(_translate("postgisQueryBuilder", "postgisQueryBuilder", None))
        self.ButtonReset.setText(_translate("postgisQueryBuilder", "reset form", None))
        self.ButtonClose.setText(_translate("postgisQueryBuilder", "close", None))
        self.FIELDLabel.setText(_translate("postgisQueryBuilder", "Select Field of Layer A", None))
        self.SPATIALRELLabel.setText(_translate("postgisQueryBuilder", "Spatial relationship between LayerA and Layer B", None))
        self.BUFFERRADIUSLabel.setText(_translate("postgisQueryBuilder", "Buffer radius", None))
        self.OPERATORLabel.setText(_translate("postgisQueryBuilder", "Operator", None))
        self.PSQLConnectionLabel.setText(_translate("postgisQueryBuilder", "Postgresql connection", None))
        self.ButtonHelp.setText(_translate("postgisQueryBuilder", "Help ", None))
        self.label.setText(_translate("postgisQueryBuilder", "Query type", None))
        self.ButtonRun.setText(_translate("postgisQueryBuilder", "Run query", None))
        self.CONDITIONLabel.setText(_translate("postgisQueryBuilder", "Condition", None))
        self.AddToMap.setText(_translate("postgisQueryBuilder", "Add to map", None))
        self.LAYERbLabel.setText(_translate("postgisQueryBuilder", "Layer B", None))
        self.LAYERaLabel.setText(_translate("postgisQueryBuilder", "Layer A", None))
        self.SPATIALRELNOT.setText(_translate("postgisQueryBuilder", "NOT", None))
        self.checkCreateView.setText(_translate("postgisQueryBuilder", "As view", None))
        self.GEOMETRYFIELDLabel.setText(_translate("postgisQueryBuilder", "Geometry field", None))
        self.KEYFIELDLabel.setText(_translate("postgisQueryBuilder", "Key field", None))
        self.checkMaterialized.setText(_translate("postgisQueryBuilder", "Materialized", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.QueryTab), _translate("postgisQueryBuilder", "Query", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TableTab), _translate("postgisQueryBuilder", "Table result", None))

